version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
  - nuget restore
build:
  project: Gadz.Tetris.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
